### ISSUE TITLE
GStreamerUnity for linux

### ISSUE THREAD

**Issue by joanllobera** [mrayy/mrayGStreamerUnity#2]
hi,
I wanted to ask what it would take to compile your plugin for linux. could you point out what parts would need to be replaced?

I can run the unity project using the compiled dll you provide, but i cannot open the VS project (see previous issue). 

we would need to do a gstreamer-unity connection within windows, but also within linux. we are therefore looking into your project to see what makes more sense, either continuing your owrk or starting from scratch.

**Comment by mrayy** [comment]
Hi,

About the visual studio issue, I am currently using Visual Studio 2013
Sorry for my mistake, I didn't update the readme file that I have changed the GStreamer SDK to x64 bit so it will support Unity much better.
Try to install the sdk from here:
http://gstreamer.freedesktop.org/data/pkg/windows/1.5.1/gstreamer-1.0-devel-x86_64-1.5.1.msi
and the runtime from here:
http://gstreamer.freedesktop.org/data/pkg/windows/1.5.1/gstreamer-1.0-x86_64-1.5.1.msi

After installed, a system variable should be added under name : GSTREAMER_SDK_ROOT_X64
This is very important in order to open project files (since I am using property manager to load gstreamer libraries to the project).

This should be it for running it under windows and compiling it.

About Linux systems, I have wrote the plugin with Cross-Platform compatibility support in mind, however I didnt have much time to write one for Linux.
In the source files, you can see several files with prefix (Win) to indicate its windows implementation. Those classes are inherited from abstract interfaces which you can reimplement them for Linux. 
There might be few other places should be taken care of (some win32 function calls), which should be very easy to address.

Last, check the implementation of BlitImage() in the file UnityHelpers.cpp, I suppose it should work fine as it is since it have OpenGL implementation, but just keep an eye on it while testing.

**Comment by NoTuxNoBux** [comment]
We have a fork that diverges quite a bit since the latest refactorings, but I wrote a meson build file that got the job done and got Unity Editor with the OpenGL back end on Arch Linux working with the plugin to stream h264 (out) over the network.

Here is the meson file:

```meson
project(
    'GStreamerUnityPlugin',
    'c', 'cpp',
    default_options : ['c_std=c17', 'cpp_std=c++17']
)

dependencies = [
    dependency('glib-2.0'),
    dependency('gio-unix-2.0'),
    dependency('gstreamer-1.0'),
    dependency('gstreamer-app-1.0'),
    dependency('gstreamer-audio-1.0'),
    dependency('gstreamer-video-1.0'),
    dependency('glew')
]

include_directories = [
    include_directories('../includes'),
    include_directories('../includes/GLEW'),
    include_directories('../sources')
]

library(
    'GStreamerUnityPlugin',
    '../sources/GStreamerCore.cpp',
    '../sources/IGStreamerPlayer.cpp',
    '../sources/IGStreamerStreamer.cpp',
    '../sources/UnityHelpers.cpp',
    '../sources/UnityImageGrabber.cpp',
    '../sources/VideoAppSinkHandler.cpp',
    '../sources/AudioAppSinkHandler.cpp',
    '../sources/GstPipelineHandler.cpp',
    '../sources/GstNetworkAudioStreamer.cpp',
    '../sources/GstCustomVideoPlayer.cpp',
    '../sources/GstNetworkAudioPlayer.cpp',
    '../sources/GstNetworkMultipleVideoPlayer.cpp',
    '../sources/GstNetworkVideoPlayer.cpp',
    '../sources/PlayersAPI.cpp',
    '../sources/CoreAPI.cpp',
    '../sources/GstPlayerBin.cpp',
    '../sources/StreamersAPI.cpp',
    '../sources/IAppSinkHandler.cpp',
    '../sources/rtp.cpp',
    '../sources/CMyListener.cpp',
    '../sources/GstNetworkVideoStreamer.cpp',
    '../sources/GstCustomVideoStreamer.cpp',
    '../sources/GstCustomDataReceiver.cpp',
    '../sources/GstAppNetAudioStreamer.cpp',
    '../sources/LocalAudioGrabber.cpp',
    '../sources/CustomAudioGrabber.cpp',
    '../sources/UnityAudioGrabber.cpp',
    '../sources/NetworkAudioGrabber.cpp',
    '../sources/GstCustomDataPlayer.cpp',
    '../sources/GstAppAudioPlayer.cpp',
    '../sources/GstCustomDataStreamer.cpp',
    '../sources/GstAudioSampler.cpp',
    '../sources/GZipCompress.cpp',
    '../sources/DirectSoundOutputStream.cpp',
    '../sources/DirectSoundInputStream.cpp',
    '../sources/CMyUDPSink.cpp',
    '../sources/CMyUDPSrc.cpp',
    '../includes/ImageInfo.cpp',
    '../includes/IThreadManager.cpp',
    '../includes/NetAddress.cpp',
    '../includes/PixelUtil.cpp',
    '../includes/UnityGraphicsDevice.cpp',
    '../includes/RenderAPI_OpenGL2.cpp',
    '../includes/RenderAPI.cpp',
    '../includes/RenderAPI_D3D9.cpp',
    '../includes/RenderAPI_D3D11.cpp',
    '../includes/Win32/Win32Network.cpp',
    '../includes/Win32/Win32UDPClient.cpp',
    '../includes/Win32/WinMutex.cpp',
    '../includes/Win32/WinThread.cpp',
    '../includes/Win32/WinThreadManager.cpp',
    '../includes/RenderAPI_OpenGLCoreES.cpp',
    '../includes/OSX/OSXMutex.cpp',
    '../includes/OSX/OSXThread.cpp',
    '../includes/OSX/OSXThreadManager.cpp',
    '../includes/GLEW/glew.c',
    '../includes/zlib/adler32.c',
    '../includes/zlib/compress.c',
    '../includes/zlib/crc32.c',
    '../includes/zlib/deflate.c',
    '../includes/zlib/gzio.c',
    '../includes/zlib/infback.c',
    '../includes/zlib/inffast.c',
    '../includes/zlib/inflate.c',
    '../includes/zlib/inftrees.c',
    '../includes/zlib/trees.c',
    '../includes/zlib/uncompr.c',
    '../includes/zlib/zutil.c',
    dependencies: dependencies,
    include_directories: include_directories,
    cpp_args: '-DUSE_UNITY_GRABBER'
)
```

Will probably need some minor changes based on files that have been removed or moved in latest master. I put it in `Plugin/Linux`.

To build, `cd` to the folder the Meson build file is, run `meson setup build` and then `meson compile`.

I build with GCC, so you will then encounter a bunch of compiler errors. Most of them are relatively easy to fix:

* Some header files have incorrect casing (Linux is case sensitive).
* Some files are missing some includes, e.g. `cstring` for `memcpy`.
* Some strictness errors where GCC is stricter than VC++.
* Some `__stdcall` relics that can be replaced with `UNITY_INTERFACE_API`.
* In `CoreAPI.cpp`, just select the `OS::OSXThreadManager()` as back end when `#ifdef __linux__` as it already uses modern C++ `std::mutex` as well as pthread stuff that just works.

Hope this helps anyone looking to port.

**Comment by realuptime** [comment]
@NoTuxNoBux Hi, Where can I find the branch that contains the meson build file?

**Comment by NoTuxNoBux** [comment]
@realuptime Apologies if my post was unclear - I mentioned we have a fork, but "we" is the company I work for, so its not open to the public. As such, I don't have a branch available (even if I did, our fork has diverged with breaking changes, so a patch wouldn't be useful), but the above instructions should make it easier to get it working :slightly_smiling_face: .

**Comment by realuptime** [comment]
Thank you!

**Comment by realuptime** [comment]
@NoTuxNoBux Linux support PR, without meson:
https://github.com/mrayy/mrayGStreamerUnity/pull/47

**Comment by QiaoJingjing** [comment]
> Linux 支持 PR，无介子：[#47](https://github.com/mrayy/mrayGStreamerUnity/pull/47)

Hi，Recently I've been trying to port the mrayGstreamerUnity plug-in to Ubuntu, but I've run into difficulties. As you can see from the logs, the so file seems to be loaded, but I can't get any more of the logs, there isn't even a boot log for the first line, so I suspect it has something to do with the so file I compiled. I'd like to ask what system the compiled so file runs on and what version of gstreamer is used, what gstreamer plugins are installed
