### ISSUE TITLE
Test scenes failed to run, Error while loading the Plugin

### ISSUE THREAD

**Issue by spaul13** [mrayy/mrayGStreamerUnity#9]
While running the test scenes, its giving error

_Failed to load 'Assets/Plugins/x86_64/GStreamerUnityPlugin.dll' with error 'The specified module could not be found.
'.
GstBaseTexture:Initialize() (at Assets/GStreamerUnity/Scripts/GstBaseTexture.cs:92)
GstBaseTexture:Initialize() (at Assets/GStreamerUnity/Scripts/GstBaseTexture.cs:88)
CustomSBSPipelinePlayer:Start() (at Assets/GStreamerUnity/Components/CustomSBSPipelinePlayer.cs:39)_

In order to generate dll using the visual studio, when I open the GStreamerUnityPlugin Solution its giving me an error of 
_Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4019	The imported project "C:\share\vs\2010\libs\gstreamer-app-1.0.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	GStreamerUnityPlugin	C:\Users\spaul\Downloads\mrayGStreamerUnity-master\mrayGStreamerUnity-master\Plugin\VS\GStreamerUnityPlugin.vcxproj	64_	

Can anyone please tell me how to solve these two problems? Any help will be highly appreciated.

**Comment by augiem** [comment]
This is due to the fact that something has changed between GStreamer 1.11 and the newest version. Probably some breaking API change. The DLL that comes with the project cannot be used with a newer version. Either use GStreamer 1.11 or you will have to rebuild the DLL for the newer version, possibly including making changes to accommodate the changes to the library.

**Comment by augiem** [comment]
This happens when the GStreamerUnityPlugin's dependencies can't be found. This is usually due to not setting up the Path environment variable as instructed in the documentation. However, it will also happen if you install the MSVC version of GStreamer instead of the MinGW version. This plugin requires the MinGW version of GStreamer on Windows.

**Comment by mikkomcmenamin** [comment]
Also note that the default environment path name for Gstreamer SDK is GSTREAMER_1_0_ROOT_X86_64 but in the GStreamerUnityPlugin.vcxproj the import statements point to the GST_SDK_PATH environment variable. Easiest fix is to add the GST_SDK_PATH to your environment variables that points to the C:\gstreamer\1.0\x86_64\ location
